services:
  react-app:
#    image: mikhailstatsenko/vitality-git-frontend
    build: .
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    ports:
      - "3000:3000"
    volumes:
      - .:/app